// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NervboxDeamon;

#nullable disable

namespace NervboxDeamon.Migrations
{
    [DbContext(typeof(NervboxDBContext))]
    [Migration("20251220130000_AddCreditSystem")]
    partial class AddCreditSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("NervboxDeamon.DbModels.CreditSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CostPerSoundPlay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cost_per_sound_play");

                    b.Property<int>("HourlyCreditsAmount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hourly_credits_amount");

                    b.Property<bool>("HourlyCreditsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hourly_credits_enabled");

                    b.Property<int>("InitialCreditsAdmin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("initial_credits_admin");

                    b.Property<int>("InitialCreditsUser")
                        .HasColumnType("INTEGER")
                        .HasColumnName("initial_credits_user");

                    b.Property<int>("MaxCreditsUser")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_credits_user");

                    b.Property<int>("MinCreditsToPlay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_credits_to_play");

                    b.HasKey("Id");

                    b.ToTable("credit_settings");
                });

            modelBuilder.Entity("NervboxDeamon.DbModels.CreditTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("INTEGER")
                        .HasColumnName("balance_after");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("RelatedEntityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_type");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("credit_transactions");
                });

            modelBuilder.Entity("NervboxDeamon.DbModels.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("GifUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("gif_url");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<int>("MessageType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("message_type");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("chat_messages");
                });

            modelBuilder.Entity("NervboxDeamon.DbModels.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingScopeString")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("SettingScope");

                    b.Property<string>("SettingTypeString")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("SettingType");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("settings");
                });

            modelBuilder.Entity("NervboxDeamon.DbModels.Sound", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.HasKey("Hash");

                    b.HasIndex("AuthorId");

                    b.ToTable("sounds");
                });

            modelBuilder.Entity("NervboxDeamon.DbModels.SoundTag", b =>
                {
                    b.Property<string>("SoundHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("sound_hash");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tag_id");

                    b.HasKey("SoundHash", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("sound_tags");
                });

            modelBuilder.Entity("NervboxDeamon.DbModels.SoundUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("played_at");

                    b.Property<string>("SoundHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sound_hash");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SoundHash");

                    b.HasIndex("UserId");

                    b.ToTable("sound_usages");
                });

            modelBuilder.Entity("NervboxDeamon.DbModels.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_pinned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags");
                });

            modelBuilder.Entity("NervboxDeamon.DbModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AvatarFileName")
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar_file_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("credits");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastCreditGrantAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_credit_grant_at");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("NervboxDeamon.DbModels.UserFavorite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<string>("SoundHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("sound_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "SoundHash");

                    b.HasIndex("SoundHash");

                    b.ToTable("user_favorites");
                });

            modelBuilder.Entity("NervboxDeamon.DbModels.ChatMessage", b =>
                {
                    b.HasOne("NervboxDeamon.DbModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NervboxDeamon.DbModels.CreditTransaction", b =>
                {
                    b.HasOne("NervboxDeamon.DbModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NervboxDeamon.DbModels.Sound", b =>
                {
                    b.HasOne("NervboxDeamon.DbModels.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("NervboxDeamon.DbModels.SoundTag", b =>
                {
                    b.HasOne("NervboxDeamon.DbModels.Sound", "Sound")
                        .WithMany("SoundTags")
                        .HasForeignKey("SoundHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NervboxDeamon.DbModels.Tag", "Tag")
                        .WithMany("SoundTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sound");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("NervboxDeamon.DbModels.SoundUsage", b =>
                {
                    b.HasOne("NervboxDeamon.DbModels.Sound", "Sound")
                        .WithMany("Usages")
                        .HasForeignKey("SoundHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NervboxDeamon.DbModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Sound");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NervboxDeamon.DbModels.UserFavorite", b =>
                {
                    b.HasOne("NervboxDeamon.DbModels.Sound", "Sound")
                        .WithMany("Favorites")
                        .HasForeignKey("SoundHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NervboxDeamon.DbModels.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sound");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NervboxDeamon.DbModels.Sound", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("SoundTags");

                    b.Navigation("Usages");
                });

            modelBuilder.Entity("NervboxDeamon.DbModels.Tag", b =>
                {
                    b.Navigation("SoundTags");
                });

            modelBuilder.Entity("NervboxDeamon.DbModels.User", b =>
                {
                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
